import { pgTable, text, timestamp, uuid, integer, boolean, pgEnum } from 'drizzle-orm/pg-core';

export const guideCategoryEnum = pgEnum('guide_category', [
  'procurement',
  'health',
  'compliance',
  'jobs',
  'salaries',
  'general',
]);

export const guides = pgTable('guides', {
  id: uuid('id').primaryKey().defaultRandom(),
  slug: text('slug').notNull().unique(),
  title: text('title').notNull(),
  summary: text('summary').notNull(),
  // Full article body stored as HTML (generated by AI, rendered with dangerouslySetInnerHTML)
  contentHtml: text('content_html').notNull(),
  category: guideCategoryEnum('category').notNull().default('general'),
  /** Which search trend triggered the last AI refresh */
  trendTopic: text('trend_topic'),
  /** Comma-separated keywords for <meta keywords> */
  keywords: text('keywords'),
  readingTimeMinutes: integer('reading_time_minutes').default(5),
  isPublished: boolean('is_published').notNull().default(true),
  publishedAt: timestamp('published_at').notNull().defaultNow(),
  updatedAt: timestamp('updated_at').notNull().defaultNow(),
  /** How many times the page has been viewed */
  viewCount: integer('view_count').notNull().default(0),
});
