var job = {};
job.title = $('meta[property="og:title"]').attr('content');
job.companyName = 'Sandvik';
job.description = $('meta[property="og:description"]').attr('content');
job.location = '';
job.jobType = '';
job.sourceUrl = $('meta[property="og:url"]').attr('content');
job.postedDateIsoString = $('meta[property="article:published_time"]').attr('content');
job.deadlineIsoString = '';
job.salaryMin = '';
job.salaryMax = '';
job.salaryCurrency = '';
result.push(job);