import { db, safeQuery } from '@/lib/db/client';
import { guides } from '@/lib/db/schema/guides';
import { eq } from 'drizzle-orm';
import { notFound } from 'next/navigation';
import Link from 'next/link';
import sanitizeHtml from 'sanitize-html';

// Allowlist of tags and attributes safe for editorial article content
const SANITIZE_OPTIONS: sanitizeHtml.IOptions = {
  allowedTags: [
    'article', 'section', 'h2', 'h3', 'h4', 'p', 'ul', 'ol', 'li',
    'strong', 'em', 'b', 'i', 'a', 'br', 'hr', 'blockquote',
    'table', 'thead', 'tbody', 'tr', 'th', 'td', 'caption',
    'code', 'pre', 'span', 'div',
  ],
  allowedAttributes: {
    'a': ['href', 'title', 'rel', 'target'],
    'span': ['class'],
    'div': ['class'],
    'p': ['class'],
    'h2': ['class'],
    'h3': ['class'],
    'table': ['class'],
  },
  allowedSchemes: ['https', 'http', 'mailto'],
  // Strip any remaining dangerous content rather than escaping it
  disallowedTagsMode: 'discard',
};

// Revalidate every hour
export const revalidate = 3600;

export async function generateMetadata(props: { params: Promise<{ slug: string }> }) {
  const params = await props.params;
  const guideList = await safeQuery(
    db.select().from(guides).where(eq(guides.slug, params.slug)).limit(1)
  );
  
  if (!guideList.length) return {};
  
  const guide = guideList[0];
  
  return {
    title: guide.title,
    description: guide.summary,
    keywords: guide.keywords,
    alternates: { canonical: `https://akilibrain.com/guides/${guide.slug}` },
    openGraph: {
      title: guide.title,
      description: guide.summary,
      url: `https://akilibrain.com/guides/${guide.slug}`,
      type: 'article',
      publishedTime: guide.publishedAt.toISOString(),
      modifiedTime: guide.updatedAt.toISOString(),
    },
  };
}

export default async function GuideDetailPage(props: { params: Promise<{ slug: string }> }) {
  const params = await props.params;
  const guideList = await safeQuery(
    db.select().from(guides).where(eq(guides.slug, params.slug)).limit(1)
  );

  if (!guideList.length) {
    notFound();
  }

  const guide = guideList[0];

  // In the background, increment view count without blocking the render
  safeQuery(
    db.update(guides)
      .set({ viewCount: guide.viewCount + 1 })
      .where(eq(guides.id, guide.id))
  ).catch(console.error);

  return (
    <div className="container mx-auto px-4 py-12 max-w-4xl">
      <div className="mb-6">
        <Link href="/guides" className="text-sm text-muted-foreground hover:text-primary transition-colors">
          ← All Guides
        </Link>
      </div>

      <article className="space-y-10">
        <header className="space-y-4">
          <div className="inline-block bg-primary/10 text-primary text-xs font-semibold px-3 py-1 rounded-full uppercase tracking-wide">
            {guide.category}
          </div>
          <h1 className="text-4xl font-bold tracking-tight leading-tight">
            {guide.title}
          </h1>
          <p className="text-xl text-muted-foreground leading-relaxed">
            {guide.summary}
          </p>
          <div className="flex items-center gap-4 text-sm text-muted-foreground pt-2 border-t border-white/10">
            <span>By the AkiliBrain Team</span>
            <span>·</span>
            <span>{guide.publishedAt.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}</span>
            <span>·</span>
            <span>{guide.readingTimeMinutes} min read</span>
            <span>·</span>
            <span>{guide.viewCount} views</span>
          </div>
        </header>

        {/* The content HTML generated by the AI is sanitized before rendering to prevent XSS */}
        <div 
          className="prose prose-invert prose-primary max-w-none prose-headings:font-semibold prose-a:text-primary hover:prose-a:underline"
          dangerouslySetInnerHTML={{ __html: sanitizeHtml(guide.contentHtml, SANITIZE_OPTIONS) }}
        />

        <nav className="border-t border-white/10 pt-6 flex flex-col sm:flex-row gap-4 justify-between">
          <Link href="/guides" className="text-sm text-muted-foreground hover:text-primary transition-colors">
            ← All Guides
          </Link>
          <Link href={`/${guide.category === 'general' ? '' : guide.category}`} className="text-sm text-primary hover:underline capitalize">
            Explore {guide.category} Data →
          </Link>
        </nav>
      </article>
    </div>
  );
}
